# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "inventory-manager"
client_id = "4262614a908de1e156112bfc9498c21d"
application_url = "https://4c62-2607-fea8-28e6-1d00-4db3-2116-fab0-2272.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_draft_orders,write_purchase_options, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://4c62-2607-fea8-28e6-1d00-4db3-2116-fab0-2272.ngrok-free.app/auth/callback",
  "https://4c62-2607-fea8-28e6-1d00-4db3-2116-fab0-2272.ngrok-free.app/auth/shopify/callback",
  "https://4c62-2607-fea8-28e6-1d00-4db3-2116-fab0-2272.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "umarttesting.myshopify.com"
